/**
 * Regression test for Capability Router stage and n8n node integration.
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { isStageName, STAGES, runStage } from '../../scripts/n8n/stage.js';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');

test('STAGES array includes router, diverge, jury, assets', () => {
  assert.ok(isStageName('router'), 'router is a valid stage');
  assert.ok(isStageName('diverge'), 'diverge is a valid stage');
  assert.ok(isStageName('jury'), 'jury is a valid stage');
  assert.ok(isStageName('assets'), 'assets is a valid stage');
  assert.ok(STAGES.includes('router'));
});

// The Factory V1 n8n workflow (`n8n/factory-v1.json`, generated by
// `scripts/n8n/build-factory-workflow.ts`) was removed 2026-08-25
// (docs/IMPLEMENTATION_GAP.md P2-1 / WORK_QUEUE.json WQ-020) — superseded by
// `n8n/businessforge-workflow.json`/`build-workflow-json.ts`, zero repo-internal
// runtime callers of `/stage/:name` beyond the route handler itself. The
// "Capability Router node in factory-v1.json" test that lived here went with
// it; `/stage/router` itself is still real and still covered below.

test('runStage(router) executes and writes 0-routes.json', async () => {
  const runId = 'test-router-' + Date.now().toString(36);
  const result = await runStage({ stage: 'router', runId });
  assert.equal(result.stage, 'router');
  assert.equal(result.runId, runId);
  assert.ok(result.note && result.note.includes('capability router'), 'note mentions capability router');

  const routesPath = path.join(REPO_ROOT, 'output', runId, '0-routes.json');
  assert.ok(fs.existsSync(routesPath), '0-routes.json was written');
  const routes = JSON.parse(fs.readFileSync(routesPath, 'utf8'));
  assert.ok(routes.research, 'routes has research capability');
  assert.ok(routes.content, 'routes has content capability');
  assert.ok(routes['design.concept'], 'routes has design.concept capability');
  assert.ok(routes['coding.frontend'], 'routes has coding.frontend capability');
});
