/**
 * Test: Real Business URL Intake & Propagation
 *
 * Verifies that businessUrl, sourceUrls, and additionalInstruction are accepted
 * at intake and propagated through brief, research, synthesis, and job records.
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { fallbackBrief } from '../../lib/factory/brief.js';
import { synthesizeResearch } from '../../lib/factory/synthesize.js';
import type { FactoryBrief } from '../../lib/factory/brief.js';
import type { ResearchNote } from '../../lib/factory/research.js';

test('fallbackBrief preserves businessUrl, sourceUrls, and additionalInstruction', () => {
  const brief = fallbackBrief('Brutarie Sibiu', {
    businessUrl: 'https://maps.google.com/?cid=123456789',
    sourceUrls: ['https://instagram.com/brutariamara_sibiu'],
    additionalInstruction: 'Highlight traditional stone-baked sourdough',
  });

  assert.equal(brief.businessUrl, 'https://maps.google.com/?cid=123456789');
  assert.deepEqual(brief.sourceUrls, ['https://instagram.com/brutariamara_sibiu']);
  assert.equal(brief.additionalInstruction, 'Highlight traditional stone-baked sourdough');
  assert.equal(brief.searchQuery, 'https://maps.google.com/?cid=123456789');
});

test('synthesizeResearch propagates businessUrl and sourceUrls into synthesis artifact', () => {
  const brief: FactoryBrief = {
    order: 'Brutarie Sibiu',
    businessType: 'artisan bakery',
    city: 'Sibiu',
    country: 'Romania',
    language: 'ro',
    searchQuery: 'brutarie artizanala sibiu',
    qualityBar: 'premium',
    businessUrl: 'https://maps.google.com/?cid=123456789',
    sourceUrls: ['https://instagram.com/brutariamara_sibiu'],
    additionalInstruction: 'Highlight stone-baked sourdough',
    authoredBy: null,
    createdAt: new Date().toISOString(),
  };

  const dummyNote: ResearchNote = {
    role: 'research',
    positioning: 'High quality artisan bakery',
    audience: 'Local sourdough enthusiasts',
    differentiators: ['Natural fermentation', 'Organic local wheat'],
    siteMustDo: ['Daily bread menu', 'Opening hours'],
    searchQueries: ['brutarie artizanala sibiu'],
    risks: ['Generic bakery styling'],
    authoredBy: {
      provider: 'gemini',
      model: 'gemini-2.5-flash',
      requestId: null,
      at: new Date().toISOString(),
    },
  };

  const synthesis = synthesizeResearch(brief, [dummyNote]);

  assert.equal(synthesis.businessUrl, 'https://maps.google.com/?cid=123456789');
  assert.deepEqual(synthesis.sourceUrls, ['https://instagram.com/brutariamara_sibiu']);
  assert.equal(synthesis.additionalInstruction, 'Highlight stone-baked sourdough');
  assert.equal(synthesis.searchQuery, 'brutarie artizanala sibiu');
});

// The Factory V1 n8n workflow (`n8n/factory-v1.json`, generated by
// `scripts/n8n/build-factory-workflow.ts`) was removed 2026-08-25
// (docs/IMPLEMENTATION_GAP.md P2-1 / WORK_QUEUE.json WQ-020) — superseded by
// `n8n/businessforge-workflow.json`/`build-workflow-json.ts`. The
// "n8n workflow contains official businessUrl..." test that asserted its
// generated node shape went with it; businessUrl/sourceUrls/additionalInstruction
// propagation itself is still covered by the two tests above, independent of
// any n8n workflow JSON.
