/**
 * Thirty more businesses, for reviewing the design layer at scale.
 *
 * Twenty was enough to see that a page looked generic; it was not enough to see
 * *which* generic. Repetition only shows up in aggregate — two sites sharing a
 * hero variant is a coincidence, eleven sharing one is the engine having a
 * favourite — and the failure this set exists to catch is the quality gate's:
 * that a luxury hotel and a bakery should not be mistakable for each other.
 *
 * The additions are chosen to stress the classifier and the layout planner
 * rather than to be pretty. Several sit deliberately close to an existing entry
 * — a wine bar beside a cocktail bar, a physiotherapist beside a dentist, a
 * barber beside a salon — because near-neighbours are where a design engine
 * gives itself away.
 *
 * Section shapes vary as hard as the categories do: some carry nine bullets and
 * eight photographs, some carry a heading and one sentence. The thin ones are
 * not padding — a real listing often *is* that thin, and a page that only looks
 * composed when the copy is generous is a page that will look broken in
 * production.
 *
 * Same rules as the first twenty: written by hand, and no palette entry carries
 * a colour, so the industry fallback hues stay under review.
 */

import { galleryImages, heroImage } from './example-images.js';

import type { ExampleSpec } from './example-businesses.js';

export const EXTRA_EXAMPLES: readonly ExampleSpec[] = [
  {
    slug: 'wine-bar',
    label: 'Wine bar',
    name: 'Sediment',
    listingCategory: 'Wine bar',
    strategyPrimary: 'Wine bar',
    strategySecondary: ['Bar', 'Small plates'],
    tagline: 'Forty bottles, no list you need a degree to read',
    tone: 'relaxed and knowledgeable',
    headingFont: 'Lora',
    bodyFont: 'Source Sans 3',
    services: ['Wine by the glass', 'Small plates', 'Private hire'],
    seoDescription: 'A small wine bar pouring low-intervention bottles by the glass, with a short plate menu.',
    sections: [
      {
        kind: 'hero',
        heading: 'Everything is open',
        subheading: 'Which means everything is by the glass',
        body: 'We pour whatever we are drinking. If a bottle is on the shelf you can have a glass of it.',
        images: [heroImage('The bar at Sediment')],
        callToAction: { label: 'See what is open', href: '#pouring' },
      },
      {
        kind: 'menu',
        heading: 'Pouring',
        bullets: [
          'Jura Chardonnay, Ganevat — 11.00',
          'Etna Rosso, Graci — 9.50',
          'Blaufränkisch, Claus Preisinger — 8.50',
          'Fino en rama, half glass — 5.00',
        ],
      },
      {
        kind: 'menu',
        heading: 'Plates',
        bullets: ['Anchovy and butter — 6.00', 'Chicory, walnut, blue — 8.00', 'Whole crab, one hour notice — 24.00'],
      },
      { kind: 'gallery', heading: 'The room', images: galleryImages(5, 'Inside Sediment') },
      { kind: 'testimonials', heading: 'Regulars', bullets: ['"They opened a 200 pound bottle so I could try one glass." — R. Vance'] },
      { kind: 'hours', heading: 'Open', bullets: ['Wednesday to Saturday, 17:00–24:00', 'Sunday, 15:00–22:00'] },
      { kind: 'contact', heading: 'Find us', bullets: ['Cellar entrance, 8 Mint Yard', 'pour@example.test'] },
    ],
  },
  {
    slug: 'cocktail-bar',
    label: 'Cocktail bar',
    name: 'Nightjar & Co',
    listingCategory: 'Cocktail bar',
    strategyPrimary: 'Bar',
    strategySecondary: ['Cocktail bar', 'Late night'],
    tagline: 'Dark room, bold drinks, no menu after midnight',
    tone: 'bold and theatrical',
    headingFont: 'Archivo',
    bodyFont: 'Archivo',
    services: ['Cocktails', 'Bartender choice', 'Late licence'],
    seoDescription: 'A basement cocktail bar with a rotating list and a late licence. Bartender choice after midnight.',
    sections: [
      {
        kind: 'hero',
        heading: 'Tell us what you like',
        subheading: 'We will take it from there',
        body: 'The list changes every six weeks. After midnight there is no list at all.',
        images: [heroImage('The bar, low light')],
        callToAction: { label: 'Book a table', href: '#contact' },
      },
      {
        kind: 'services',
        heading: 'What we do',
        bullets: [
          'Signature list, six weeks a rotation',
          'Bartender choice, tell us a spirit and a mood',
          'Classics, made properly, no theatre',
          'Zero proof, built not substituted',
          'Bar hire, Sunday and Monday',
        ],
      },
      { kind: 'gallery', heading: 'The room', images: galleryImages(6, 'Nightjar interior') },
      { kind: 'testimonials', heading: 'What people say', bullets: ['"Best drink I have had in this city, and I did not order it." — D. Okafor'] },
      { kind: 'hours', heading: 'Open', bullets: ['Tuesday to Thursday, 18:00–01:00', 'Friday and Saturday, 18:00–03:00'] },
      { kind: 'contact', heading: 'Contact', bullets: ['bookings@example.test', '020 0000 0000'] },
      { kind: 'cta', heading: 'Walk-ins after 11', subheading: 'The bar is always kept for them', callToAction: { label: 'Reserve earlier', href: '#contact' } },
    ],
  },
  {
    slug: 'butcher',
    label: 'Butcher',
    name: 'Hindmarsh & Son',
    listingCategory: 'Butcher shop',
    strategyPrimary: 'Butcher',
    strategySecondary: ['Food retail'],
    tagline: 'Whole carcass, hung four weeks',
    tone: 'plain and traditional',
    headingFont: 'Nunito Sans',
    bodyFont: 'Nunito Sans',
    services: ['Dry-aged beef', 'Sausages', 'Game in season', 'Butchery classes'],
    seoDescription: 'A traditional butcher buying whole carcass from named farms and dry-ageing on the bone.',
    sections: [
      {
        kind: 'hero',
        heading: 'One farm at a time',
        subheading: 'We buy the whole animal or none of it',
        body: 'Three farms, all within forty miles. The board says which one you are eating.',
        images: [heroImage('The counter')],
        callToAction: { label: 'This week', href: '#counter' },
      },
      {
        kind: 'menu',
        heading: 'The counter',
        bullets: [
          'Dry-aged sirloin, 28 days — 34.00/kg',
          'Native breed mince — 11.00/kg',
          'Lincolnshire sausage — 9.50/kg',
          'Bone broth bones — 3.00/kg',
        ],
      },
      { kind: 'gallery', heading: 'The shop', images: galleryImages(4, 'In the shop') },
      { kind: 'hours', heading: 'Open', bullets: ['Tuesday to Friday, 08:00–17:30', 'Saturday, 08:00–16:00', 'Closed Sunday and Monday'] },
      { kind: 'location', heading: 'Where', body: '3 Shambles Row' },
      { kind: 'contact', heading: 'Contact', bullets: ['orders@example.test', '01522 000 000'] },
    ],
  },
  {
    slug: 'brewery',
    label: 'Brewery',
    name: 'Cold Harbour Brewing',
    listingCategory: 'Brewery',
    strategyPrimary: 'Brewery',
    strategySecondary: ['Taproom'],
    tagline: 'Brewed in the arches, drunk in the arches',
    tone: 'direct and unpretentious',
    headingFont: 'Space Grotesk',
    bodyFont: 'Work Sans',
    services: ['Core range', 'Taproom', 'Brewery tours', 'Trade sales'],
    seoDescription: 'A railway-arch brewery with a taproom on site. Core range, specials and Saturday tours.',
    sections: [
      {
        kind: 'hero',
        heading: 'Fresh means fifty feet',
        subheading: 'The tanks are behind the bar',
        body: 'Six on tap, four of them ours, and the other two are from people we like.',
        images: [heroImage('Fermentation tanks')],
        callToAction: { label: 'What is on', href: '#on-tap' },
      },
      {
        kind: 'services',
        heading: 'What we brew',
        bullets: [
          'Pale — 4.2%, the one we started with',
          'Dark mild — 3.6%, brewed all year despite advice',
          'Saison — 5.8%, bottle conditioned',
          'Specials — one tank, never repeated',
          'Trade kegs — 30L and 50L',
          'Growler fills — bring your own',
        ],
      },
      { kind: 'gallery', heading: 'The arches', images: galleryImages(7, 'Cold Harbour') },
      { kind: 'faq', heading: 'Questions', bullets: ['Do you do tours? Saturdays at 2, book ahead.', 'Is it dog friendly? Yes, in the taproom.', 'Can we hire it? Sunday to Wednesday.'] },
      { kind: 'hours', heading: 'Taproom', bullets: ['Thursday and Friday, 16:00–23:00', 'Saturday, 12:00–23:00'] },
      { kind: 'contact', heading: 'Contact', bullets: ['beer@example.test', '0113 000 0000'] },
    ],
  },
  {
    slug: 'boutique-hotel',
    label: 'Boutique hotel',
    name: 'The Alderley',
    listingCategory: 'Boutique hotel',
    strategyPrimary: 'Hotel',
    strategySecondary: ['Luxury', 'Boutique'],
    tagline: 'Nine rooms in a house that was never a hotel',
    tone: 'quiet and exacting',
    headingFont: 'Cormorant Garamond',
    bodyFont: 'Jost',
    services: ['Rooms', 'Dining', 'Private hire'],
    seoDescription: 'A nine-room boutique hotel in a Georgian townhouse, with a bespoke dining room and no reception desk.',
    sections: [
      {
        kind: 'hero',
        heading: 'There is no front desk',
        subheading: 'Somebody will be expecting you',
        body: 'A luxury of scale rather than of gilt: nine rooms, one kitchen, and a bespoke key for each door.',
        images: [heroImage('The drawing room')],
        callToAction: { label: 'Check availability', href: '#contact' },
      },
      { kind: 'gallery', heading: 'The house', images: galleryImages(8, 'The Alderley') },
      {
        kind: 'services',
        heading: 'Staying',
        bullets: [
          'Nine rooms, no two alike',
          'Dining, thirty covers, one sitting',
          'The whole house, exclusively',
        ],
      },
      { kind: 'about', heading: 'The house', body: 'Built in 1789 for a cloth merchant and lived in continuously until 2019. We have changed the plumbing and almost nothing else.' },
      { kind: 'testimonials', heading: 'Guests', bullets: ['"We have stayed in grander places and not one as considered." — H. Lindqvist'] },
      { kind: 'contact', heading: 'Enquiries', bullets: ['stay@example.test', '01625 000 000'] },
    ],
  },
  {
    slug: 'barber',
    label: 'Barber',
    name: 'Crown & Blade',
    listingCategory: 'Barber shop',
    strategyPrimary: 'Barber',
    strategySecondary: ['Grooming'],
    tagline: 'Six chairs, no appointments, no nonsense',
    tone: 'friendly and blunt',
    headingFont: 'Manrope',
    bodyFont: 'Manrope',
    services: ['Cuts', 'Hot towel shave', 'Beard trim'],
    seoDescription: 'A walk-in barber shop with six chairs. Cuts, hot towel shaves and beard work, no appointments.',
    sections: [
      {
        kind: 'hero',
        heading: 'Walk in, sit down',
        subheading: 'The wait is on the board by the door',
        body: 'Six chairs and no booking system. It has worked for eleven years.',
        images: [heroImage('The shop floor')],
        callToAction: { label: 'See prices', href: '#prices' },
      },
      {
        kind: 'menu',
        heading: 'Prices',
        bullets: ['Cut — 22.00', 'Cut and beard — 30.00', 'Hot towel shave — 28.00', 'Under 12 — 14.00', 'Over 65 — 16.00'],
      },
      { kind: 'gallery', heading: 'The shop', images: galleryImages(4, 'Crown & Blade') },
      { kind: 'hours', heading: 'Open', bullets: ['Monday to Friday, 09:00–19:00', 'Saturday, 08:00–17:00'] },
      { kind: 'location', heading: 'Where', body: 'Under the arch, 22 Ferry Lane' },
    ],
  },
  {
    slug: 'tattoo-studio',
    label: 'Tattoo studio',
    name: 'Blackwater Tattoo',
    listingCategory: 'Tattoo shop',
    strategyPrimary: 'Tattoo studio',
    strategySecondary: ['Art', 'Body art'],
    tagline: 'Custom only, booked by the artist',
    tone: 'creative and uncompromising',
    headingFont: 'Space Grotesk',
    bodyFont: 'Work Sans',
    services: ['Custom work', 'Cover-ups', 'Guest artists'],
    seoDescription: 'A custom-only tattoo studio. Five resident artists, guest spots monthly, consultation before booking.',
    sections: [
      {
        kind: 'hero',
        heading: 'We do not do flash',
        subheading: 'Every piece starts as a conversation',
        body: 'Bring a reference, an idea, or nothing at all. The drawing happens before the deposit.',
        images: [heroImage('The studio')],
        callToAction: { label: 'See the work', href: '#portfolio' },
      },
      { kind: 'gallery', heading: 'Portfolio', images: galleryImages(9, 'Work by the studio') },
      {
        kind: 'services',
        heading: 'The artists',
        bullets: [
          'Ines — blackwork and ornamental',
          'Rae — fine line and botanical',
          'Tomas — traditional Japanese',
          'Bel — colour realism',
          'Guest chair — monthly, announced late',
        ],
      },
      { kind: 'faq', heading: 'Before you book', bullets: ['Do you take walk-ins? No.', 'What is the deposit? 80, off the final price.', 'Do you cover up? Yes, bring a photo first.'] },
      { kind: 'contact', heading: 'Contact', bullets: ['studio@example.test'] },
    ],
  },
  {
    slug: 'yoga-studio',
    label: 'Yoga studio',
    name: 'Long Room Yoga',
    listingCategory: 'Yoga studio',
    strategyPrimary: 'Yoga studio',
    strategySecondary: ['Wellness', 'Fitness'],
    tagline: 'One room, sprung floor, thirty mats',
    tone: 'calm and welcoming',
    headingFont: 'Outfit',
    bodyFont: 'Outfit',
    services: ['Classes', 'Beginner courses', 'Teacher training'],
    seoDescription: 'A single-room yoga studio with a sprung floor. Daily classes, six-week beginner courses, no membership.',
    sections: [
      {
        kind: 'hero',
        heading: 'Come as you are',
        subheading: 'No membership, no contract, no app',
        body: 'Pay for the class you take. If it is your first, arrive ten minutes early and say so.',
        images: [heroImage('The studio floor')],
        callToAction: { label: 'See the timetable', href: '#timetable' },
      },
      {
        kind: 'services',
        heading: 'Classes',
        bullets: [
          'Vinyasa — 75 minutes, moderate',
          'Slow flow — 60 minutes, all levels',
          'Restorative — 60 minutes, props provided',
          'Beginners — six weeks, one cohort',
          'Pregnancy — 60 minutes, from 14 weeks',
        ],
      },
      { kind: 'gallery', heading: 'The room', images: galleryImages(4, 'Long Room') },
      { kind: 'hours', heading: 'Timetable', bullets: ['Weekday mornings, 07:00 and 09:30', 'Weekday evenings, 18:00 and 19:45', 'Saturday, 09:00 and 11:00'] },
      { kind: 'contact', heading: 'Contact', bullets: ['hello@example.test', '0117 000 0000'] },
      { kind: 'cta', heading: 'First class is 5', subheading: 'Mat included', callToAction: { label: 'Book it', href: '#contact' } },
    ],
  },
  {
    slug: 'physiotherapy',
    label: 'Physiotherapy',
    name: 'Trent Physio',
    listingCategory: 'Physical therapist',
    strategyPrimary: 'Physiotherapy',
    strategySecondary: ['Healthcare', 'Sports injury'],
    tagline: 'Assessment, plan, discharge',
    tone: 'professional and reassuring',
    headingFont: 'IBM Plex Sans',
    bodyFont: 'IBM Plex Sans',
    services: ['Musculoskeletal', 'Post-operative', 'Sports injury', 'Home visits'],
    seoDescription: 'Chartered physiotherapists offering musculoskeletal, post-operative and sports injury care. No referral needed.',
    sections: [
      {
        kind: 'hero',
        heading: 'You do not need a referral',
        subheading: 'Chartered physiotherapists, self-referral welcome',
        body: 'Most people are assessed within a week and know their plan before they leave.',
        images: [heroImage('A treatment room')],
        callToAction: { label: 'Book an assessment', href: '#contact' },
      },
      {
        kind: 'services',
        heading: 'What we treat',
        bullets: [
          'Back and neck pain',
          'Post-operative rehabilitation',
          'Sports and overuse injury',
          'Persistent pain, graded programmes',
          'Falls and balance',
          'Home visits within the city',
        ],
      },
      { kind: 'faq', heading: 'Common questions', bullets: ['Do I need a GP referral? No.', 'Will you write to my consultant? Yes, on request.', 'Do you take insurance? All the major insurers.'] },
      { kind: 'testimonials', heading: 'Patients', bullets: ['"Discharged in five sessions when I expected fifteen." — M. Achebe'] },
      { kind: 'hours', heading: 'Clinic hours', bullets: ['Monday to Friday, 08:00–19:00', 'Saturday, 09:00–13:00'] },
      { kind: 'contact', heading: 'Contact', bullets: ['clinic@example.test', '0115 000 0000'] },
    ],
  },
  {
    slug: 'veterinary',
    label: 'Veterinary practice',
    name: 'Ashcroft Veterinary',
    listingCategory: 'Veterinarian',
    strategyPrimary: 'Veterinary practice',
    strategySecondary: ['Animal health'],
    tagline: 'Independent since 1988',
    tone: 'warm and trusted',
    headingFont: 'Nunito Sans',
    bodyFont: 'Nunito Sans',
    services: ['Consultations', 'Surgery', 'Dentistry', 'Out of hours'],
    seoDescription: 'An independent veterinary practice offering consultations, surgery, dentistry and its own out-of-hours cover.',
    sections: [
      {
        kind: 'hero',
        heading: 'The same vet, every visit',
        subheading: 'Independent, and staying that way',
        body: 'We have never been part of a group. You see the person who knows the animal.',
        images: [heroImage('The consulting room')],
        callToAction: { label: 'Register a pet', href: '#contact' },
      },
      {
        kind: 'services',
        heading: 'Services',
        bullets: [
          'Consultations and vaccination',
          'Soft tissue and orthopaedic surgery',
          'Dentistry, with digital radiography',
          'In-house laboratory, same-day results',
          'Our own out-of-hours cover',
        ],
      },
      { kind: 'about', heading: 'The practice', body: 'Founded in 1988 above what was then a saddlery. Four vets, six nurses, and the same phone number for thirty-seven years.' },
      { kind: 'hours', heading: 'Opening hours', bullets: ['Monday to Friday, 08:30–18:30', 'Saturday, 09:00–12:30', 'Out of hours, on the same number'] },
      { kind: 'contact', heading: 'Contact', bullets: ['reception@example.test', '01298 000 000'] },
    ],
  },
  {
    slug: 'optician',
    label: 'Optician',
    name: 'Field & Marr Opticians',
    listingCategory: 'Optician',
    strategyPrimary: 'Optician',
    strategySecondary: ['Eyecare', 'Retail'],
    tagline: 'Forty-minute tests, independent frames',
    tone: 'precise and unhurried',
    headingFont: 'Outfit',
    bodyFont: 'Outfit',
    services: ['Eye examinations', 'Contact lenses', 'Frames', 'Dispensing'],
    seoDescription: 'Independent opticians with forty-minute eye examinations, OCT imaging and frames from small makers.',
    sections: [
      {
        kind: 'hero',
        heading: 'Forty minutes, not twenty',
        subheading: 'Because half of what we find is not about glasses',
        body: 'Every examination includes OCT imaging, and we will show you the scan.',
        images: [heroImage('The testing room')],
        callToAction: { label: 'Book a test', href: '#contact' },
      },
      {
        kind: 'services',
        heading: 'What we offer',
        bullets: [
          'Full eye examination, forty minutes',
          'OCT retinal imaging, included',
          'Contact lens fitting and aftercare',
          'Children, from three years',
          'Frames from independent makers',
        ],
      },
      { kind: 'gallery', heading: 'The practice', images: galleryImages(5, 'Field & Marr') },
      { kind: 'hours', heading: 'Open', bullets: ['Tuesday to Friday, 09:00–17:30', 'Saturday, 09:00–16:00'] },
      { kind: 'contact', heading: 'Contact', bullets: ['appointments@example.test', '0161 000 0000'] },
    ],
  },
  {
    slug: 'pharmacy',
    label: 'Pharmacy',
    name: 'Cross Green Pharmacy',
    listingCategory: 'Pharmacy',
    strategyPrimary: 'Pharmacy',
    strategySecondary: ['Healthcare'],
    tagline: 'Open when the surgery is not',
    tone: 'plain and dependable',
    headingFont: 'IBM Plex Sans',
    bodyFont: 'IBM Plex Sans',
    services: ['Dispensing', 'Vaccination', 'Blood pressure checks', 'Delivery'],
    seoDescription: 'A community pharmacy with late and weekend hours, vaccination clinics and free local delivery.',
    sections: [
      {
        kind: 'hero',
        heading: 'Open until eight, seven days',
        subheading: 'Including bank holidays',
        body: 'Prescriptions, advice, and a consultation room if you would rather not talk at the counter.',
        images: [heroImage('The dispensary')],
        callToAction: { label: 'Services', href: '#services' },
      },
      {
        kind: 'services',
        heading: 'Services',
        bullets: [
          'NHS and private dispensing',
          'Flu and travel vaccination',
          'Blood pressure and cholesterol checks',
          'Emergency contraception',
          'Free delivery inside the ring road',
          'Monitored dosage systems',
        ],
      },
      { kind: 'hours', heading: 'Opening hours', bullets: ['Monday to Friday, 08:00–20:00', 'Saturday and Sunday, 09:00–18:00'] },
      { kind: 'location', heading: 'Where', body: 'Unit 4, Cross Green Parade' },
      { kind: 'contact', heading: 'Contact', bullets: ['0113 000 0000'] },
    ],
  },
  {
    slug: 'estate-agent',
    label: 'Estate agent',
    name: 'Marchbank Residential',
    listingCategory: 'Real estate agency',
    strategyPrimary: 'Estate agency',
    strategySecondary: ['Property', 'Lettings'],
    tagline: 'Prime and period, one postcode',
    tone: 'assured and premium',
    headingFont: 'Outfit',
    bodyFont: 'Outfit',
    services: ['Sales', 'Lettings', 'Valuations', 'Property management'],
    seoDescription: 'An estate agency specialising in period and prime residential property in a single postcode.',
    sections: [
      {
        kind: 'hero',
        heading: 'We only sell here',
        subheading: 'One postcode, since 1996',
        body: 'A premium listing is not a bigger photograph. It is knowing which of eleven buyers will pay for a garden wall.',
        images: [heroImage('A Victorian terrace')],
        callToAction: { label: 'Request a valuation', href: '#contact' },
      },
      { kind: 'gallery', heading: 'Recently sold', images: galleryImages(6, 'Sold by Marchbank') },
      {
        kind: 'services',
        heading: 'What we do',
        bullets: [
          'Sales, sole agency',
          'Lettings and full management',
          'Probate and matrimonial valuations',
          'Refurbishment advice before listing',
        ],
      },
      { kind: 'testimonials', heading: 'Clients', bullets: ['"Sold in nine days at over asking, and they talked us out of the first offer." — J. Farrer'] },
      { kind: 'contact', heading: 'Offices', bullets: ['sales@example.test', '020 0000 0000'] },
    ],
  },
  {
    slug: 'interior-design',
    label: 'Interior design',
    name: 'Hessle Studio',
    listingCategory: 'Interior designer',
    strategyPrimary: 'Interior design',
    strategySecondary: ['Design', 'Residential'],
    tagline: 'Bespoke residential interiors',
    tone: 'refined and considered',
    headingFont: 'Playfair Display',
    bodyFont: 'Source Serif 4',
    services: ['Full design', 'Concept only', 'Joinery design', 'Procurement'],
    seoDescription: 'A residential interior design studio working on bespoke whole-house projects and joinery.',
    sections: [
      {
        kind: 'hero',
        heading: 'Rooms that were always going to be that way',
        subheading: 'Bespoke residential interiors',
        body: 'We take on four projects a year. Each one starts with a month of doing nothing but looking.',
        images: [heroImage('A finished drawing room')],
        callToAction: { label: 'See the work', href: '#work' },
      },
      { kind: 'gallery', heading: 'Work', images: galleryImages(8, 'Hessle Studio project') },
      {
        kind: 'services',
        heading: 'How we work',
        bullets: [
          'Survey and brief — four weeks, no drawings',
          'Concept — plans, palette, one direction only',
          'Detail — joinery, lighting, specification',
          'Delivery — procurement, install, snagging',
        ],
      },
      { kind: 'about', heading: 'The studio', body: 'Founded in 2014. Three designers, one workshop, and a joiner who has said no to us more usefully than anyone.' },
      { kind: 'contact', heading: 'Enquiries', bullets: ['studio@example.test'] },
    ],
  },
  {
    slug: 'landscaping',
    label: 'Landscaping',
    name: 'Marlow Groundworks',
    listingCategory: 'Landscaper',
    strategyPrimary: 'Landscaping',
    strategySecondary: ['Construction', 'Garden design'],
    tagline: 'Hard landscaping, done once',
    tone: 'practical and confident',
    headingFont: 'Archivo',
    bodyFont: 'Archivo',
    services: ['Patios and paving', 'Retaining walls', 'Drainage', 'Fencing'],
    seoDescription: 'Hard landscaping contractors: paving, retaining walls, drainage and fencing, with a ten-year guarantee.',
    sections: [
      {
        kind: 'hero',
        heading: 'Dig it properly or do it twice',
        subheading: 'Ten-year guarantee on every base',
        body: 'Most of what goes wrong with a patio is under it. That is where we spend the time.',
        images: [heroImage('A finished terrace')],
        callToAction: { label: 'Recent work', href: '#work' },
      },
      { kind: 'gallery', heading: 'Recent work', images: galleryImages(6, 'Marlow Groundworks') },
      {
        kind: 'services',
        heading: 'What we do',
        bullets: [
          'Patios and paving, on a full sub-base',
          'Retaining walls, engineer designed over 1.2m',
          'Drainage and soakaways',
          'Fencing and gates',
          'Driveways, permeable as standard',
        ],
      },
      { kind: 'testimonials', heading: 'Clients', bullets: ['"Third contractor we asked and the only one who mentioned drainage." — S. Whitlock'] },
      { kind: 'contact', heading: 'Get a quote', bullets: ['quotes@example.test', '01628 000 000'] },
    ],
  },
  {
    slug: 'electrician',
    label: 'Electrician',
    name: 'Verge Electrical',
    listingCategory: 'Electrician',
    strategyPrimary: 'Electrical contractor',
    strategySecondary: ['Trades'],
    tagline: 'Certified, insured, on time',
    tone: 'straightforward',
    headingFont: 'Nunito Sans',
    bodyFont: 'Nunito Sans',
    services: ['Rewires', 'Consumer units', 'EV chargers', 'Testing'],
    seoDescription: 'NICEIC-registered electricians: rewires, consumer units, EV charger installation and periodic testing.',
    sections: [
      {
        kind: 'hero',
        heading: 'We turn up when we said',
        subheading: 'NICEIC registered, fully insured',
        body: 'A two-hour window, not a day. If we are late you hear from us before you have to ask.',
        images: [heroImage('A consumer unit')],
        callToAction: { label: 'Book a visit', href: '#contact' },
      },
      {
        kind: 'services',
        heading: 'What we do',
        bullets: [
          'Full and partial rewires',
          'Consumer unit replacement',
          'EV charger installation, OZEV approved',
          'EICR testing for landlords',
          'Fault finding, first hour fixed price',
        ],
      },
      { kind: 'faq', heading: 'Questions', bullets: ['Do you charge a call-out? No.', 'How fast is an EICR? Same week, usually.', 'Are you insured? Two million public liability.'] },
      { kind: 'contact', heading: 'Contact', bullets: ['book@example.test', '0191 000 0000'] },
    ],
  },
  {
    slug: 'plumbing',
    label: 'Plumbing and heating',
    name: 'Ashdown Plumbing & Heating',
    listingCategory: 'Plumber',
    strategyPrimary: 'Plumbing and heating',
    strategySecondary: ['Trades', 'Emergency'],
    tagline: 'Boilers, bathrooms, burst pipes',
    tone: 'reassuring and direct',
    headingFont: 'Manrope',
    bodyFont: 'Manrope',
    services: ['Boiler installation', 'Servicing', 'Bathrooms', 'Emergency callout'],
    seoDescription: 'Gas Safe registered plumbers and heating engineers. Boiler installation, servicing, bathrooms and emergencies.',
    sections: [
      {
        kind: 'hero',
        heading: 'The water is off. Now what.',
        subheading: 'Gas Safe registered, 24 hours',
        body: 'Emergency cover every day of the year, and a fixed price before anything is opened up.',
        images: [heroImage('A new boiler install')],
        callToAction: { label: 'Call now', href: '#contact' },
      },
      {
        kind: 'services',
        heading: 'What we do',
        bullets: [
          'Boiler installation and upgrade',
          'Annual servicing and gas safety certificates',
          'Bathroom installation, start to finish',
          'Leaks, burst pipes, emergency isolation',
          'Underfloor heating',
        ],
      },
      { kind: 'hours', heading: 'When we work', bullets: ['Standard hours, Monday to Friday 08:00–17:00', 'Emergency cover, 24 hours, every day'] },
      { kind: 'contact', heading: 'Contact', bullets: ['0161 000 0000', 'help@example.test'] },
      { kind: 'cta', heading: 'No call-out charge', subheading: 'You pay for the work, not the van', callToAction: { label: 'Get a price', href: '#contact' } },
    ],
  },
  {
    slug: 'driving-school',
    label: 'Driving school',
    name: 'Fenwick Driving School',
    listingCategory: 'Driving school',
    strategyPrimary: 'Driving instruction',
    strategySecondary: ['Education'],
    tagline: 'Pass first time, most of the time',
    tone: 'encouraging and plain',
    headingFont: 'Nunito Sans',
    bodyFont: 'Nunito Sans',
    services: ['Manual lessons', 'Automatic lessons', 'Intensive courses', 'Pass Plus'],
    seoDescription: 'A local driving school with DVSA-approved instructors, manual and automatic, and intensive courses.',
    sections: [
      {
        kind: 'hero',
        heading: 'Nervous is normal',
        subheading: 'We teach a lot of people who nearly did not call',
        body: 'First lesson is in a quiet estate, and you will not go near a roundabout until you want to.',
        images: [heroImage('A learner car')],
        callToAction: { label: 'Book a first lesson', href: '#contact' },
      },
      {
        kind: 'menu',
        heading: 'Prices',
        bullets: ['Single lesson — 38.00', 'Block of ten — 350.00', 'Intensive week — 1,150.00', 'Pass Plus — 220.00'],
      },
      { kind: 'faq', heading: 'Questions', bullets: ['Manual or automatic? Both.', 'Do you use my car for the test? Ours, included.', 'How many lessons will I need? Forty is the national average.'] },
      { kind: 'contact', heading: 'Contact', bullets: ['learn@example.test', '07700 000000'] },
    ],
  },
  {
    slug: 'nursery',
    label: 'Nursery',
    name: 'Bramble Lane Nursery',
    listingCategory: 'Day care center',
    strategyPrimary: 'Childcare',
    strategySecondary: ['Education', 'Early years'],
    tagline: 'Outdoors in all but the worst of it',
    tone: 'warm and playful',
    headingFont: 'Fredoka',
    bodyFont: 'Nunito',
    services: ['Under twos', 'Preschool', 'Holiday club', 'Funded hours'],
    seoDescription: 'A nursery with a large outdoor space, funded hours and a forest school session every week.',
    sections: [
      {
        kind: 'hero',
        heading: 'Mud is part of it',
        subheading: 'Please send a spare jumper',
        body: 'We are outside every day. There is a fun, noisy half-acre behind the building and we use all of it.',
        images: [heroImage('The garden')],
        callToAction: { label: 'Arrange a visit', href: '#contact' },
      },
      {
        kind: 'services',
        heading: 'Rooms',
        bullets: [
          'Acorns — under two, one to three',
          'Saplings — two to three',
          'Oaks — preschool, school ready',
          'Forest school — every Wednesday',
          'Holiday club — four to eight',
        ],
      },
      { kind: 'gallery', heading: 'A day here', images: galleryImages(6, 'Bramble Lane') },
      { kind: 'faq', heading: 'Questions', bullets: ['Do you take funded hours? 15 and 30.', 'What are the ratios? Better than statutory in every room.', 'Can we visit? Any Tuesday afternoon.'] },
      { kind: 'hours', heading: 'Open', bullets: ['Monday to Friday, 07:30–18:00', 'Closed for two weeks at Christmas'] },
      { kind: 'contact', heading: 'Contact', bullets: ['hello@example.test', '0114 000 0000'] },
    ],
  },
  {
    slug: 'music-school',
    label: 'Music school',
    name: 'Fret & Bow',
    listingCategory: 'Music school',
    strategyPrimary: 'Music tuition',
    strategySecondary: ['Education', 'Arts'],
    tagline: 'Lessons for people who were told they could not',
    tone: 'encouraging and creative',
    headingFont: 'Space Grotesk',
    bodyFont: 'Work Sans',
    services: ['Guitar', 'Piano', 'Strings', 'Theory'],
    seoDescription: 'A music school teaching guitar, piano, strings and theory to adults and children, grades optional.',
    sections: [
      {
        kind: 'hero',
        heading: 'Grades are optional here',
        subheading: 'So is reading music, to start with',
        body: 'Half our adult students came back to an instrument they gave up at fourteen.',
        images: [heroImage('A teaching room')],
        callToAction: { label: 'Book a trial', href: '#contact' },
      },
      {
        kind: 'services',
        heading: 'What we teach',
        bullets: [
          'Guitar — acoustic, electric, bass',
          'Piano — classical and by ear',
          'Strings — violin, viola, cello',
          'Voice — one to one',
          'Theory — grades 1 to 8',
          'Ensemble — Saturday mornings',
        ],
      },
      { kind: 'testimonials', heading: 'Students', bullets: ['"I am forty-six and I played in front of people last month." — K. Adeyemi'] },
      { kind: 'contact', heading: 'Contact', bullets: ['lessons@example.test', '0121 000 0000'] },
    ],
  },
  {
    slug: 'coworking',
    label: 'Coworking space',
    name: 'The Foundry Works',
    listingCategory: 'Coworking space',
    strategyPrimary: 'Coworking',
    strategySecondary: ['Workspace', 'Business services'],
    tagline: 'Desks in a building that used to make things',
    tone: 'modern and functional',
    headingFont: 'Manrope',
    bodyFont: 'Manrope',
    services: ['Hot desks', 'Fixed desks', 'Private studios', 'Meeting rooms'],
    seoDescription: 'A coworking space in a converted foundry: hot desks, fixed desks, private studios and meeting rooms.',
    sections: [
      {
        kind: 'hero',
        heading: 'Twenty-four hour access, actual daylight',
        subheading: 'Nine metre ceilings and the original crane rail',
        body: 'A modern workspace in a 1920s foundry. Contemporary fit-out, nothing about it is open plan by default.',
        images: [heroImage('The main floor')],
        callToAction: { label: 'Book a tour', href: '#contact' },
      },
      {
        kind: 'services',
        heading: 'Membership',
        bullets: [
          'Hot desk — 180 a month',
          'Fixed desk — 280 a month',
          'Private studio, 2 to 12 — from 700',
          'Meeting rooms — free credits monthly',
          'Day pass — 25',
          'Registered address — 20 a month',
        ],
      },
      { kind: 'gallery', heading: 'The building', images: galleryImages(7, 'The Foundry Works') },
      { kind: 'faq', heading: 'Questions', bullets: ['Is there parking? Twelve spaces, first come.', 'Can I get post here? Yes, included.', 'Is it 24 hour? For fixed desks and studios.'] },
      { kind: 'contact', heading: 'Contact', bullets: ['hello@example.test', '0161 000 0000'] },
    ],
  },
  {
    slug: 'recruitment',
    label: 'Recruitment',
    name: 'Ridley Search',
    listingCategory: 'Employment agency',
    strategyPrimary: 'Executive search',
    strategySecondary: ['Recruitment', 'Professional services'],
    tagline: 'Retained search, three roles at a time',
    tone: 'professional and established',
    headingFont: 'IBM Plex Sans',
    bodyFont: 'IBM Plex Sans',
    services: ['Executive search', 'Board appointments', 'Market mapping'],
    seoDescription: 'A retained executive search firm working on three mandates at a time across industrials and healthcare.',
    sections: [
      {
        kind: 'hero',
        heading: 'Three mandates at a time',
        subheading: 'Which is why we finish them',
        body: 'Retained search, one consultant per mandate, and a shortlist you could hire all of.',
        images: [heroImage('The boardroom')],
        callToAction: { label: 'Discuss a mandate', href: '#contact' },
      },
      {
        kind: 'services',
        heading: 'Practice areas',
        bullets: [
          'Chief executive and managing director',
          'Finance, CFO and financial control',
          'Operations and supply chain',
          'Non-executive and board advisory',
        ],
      },
      { kind: 'about', heading: 'The firm', body: 'Established in 2003. Six consultants, two researchers, and a completion rate we will show you before you ask.' },
      { kind: 'testimonials', heading: 'Clients', bullets: ['"They withdrew a candidate we liked because they were not convinced. That is the whole reason we use them." — Chair, industrial group'] },
      { kind: 'contact', heading: 'Contact', bullets: ['search@example.test', '020 0000 0000'] },
    ],
  },
  {
    slug: 'marketing-agency',
    label: 'Marketing agency',
    name: 'Signal & Noise',
    listingCategory: 'Marketing agency',
    strategyPrimary: 'Marketing agency',
    strategySecondary: ['Creative', 'Brand'],
    tagline: 'Brand, campaign, and the awkward questions first',
    tone: 'bold and creative',
    headingFont: 'Space Grotesk',
    bodyFont: 'Work Sans',
    services: ['Brand strategy', 'Campaigns', 'Content', 'Media'],
    seoDescription: 'An independent creative agency working on brand strategy, campaigns and content for challenger businesses.',
    sections: [
      {
        kind: 'hero',
        heading: 'Most briefs are the wrong brief',
        subheading: 'We would rather find that out in week one',
        body: 'A creative agency for businesses that are not the biggest in their category and do not intend to stay that way.',
        images: [heroImage('The studio wall')],
        callToAction: { label: 'See the work', href: '#work' },
      },
      { kind: 'gallery', heading: 'Work', images: galleryImages(8, 'Signal & Noise campaign') },
      {
        kind: 'services',
        heading: 'What we do',
        bullets: [
          'Brand strategy and positioning',
          'Identity and design systems',
          'Campaign, through the line',
          'Content, made not commissioned',
          'Media planning and buying',
          'Measurement that survives a board meeting',
        ],
      },
      { kind: 'testimonials', heading: 'Clients', bullets: ['"They told us our positioning was wrong in the pitch. They won the pitch." — Marketing director, food brand'] },
      { kind: 'contact', heading: 'Contact', bullets: ['hello@example.test'] },
      { kind: 'cta', heading: 'Got something difficult?', subheading: 'Those are the good ones', callToAction: { label: 'Start a conversation', href: '#contact' } },
    ],
  },
  {
    slug: 'bookshop',
    label: 'Bookshop',
    name: 'Quire Books',
    listingCategory: 'Book store',
    strategyPrimary: 'Bookshop',
    strategySecondary: ['Retail', 'Independent'],
    tagline: 'Everything on the table was read by somebody here',
    tone: 'literary and warm',
    headingFont: 'Playfair Display',
    bodyFont: 'Source Serif 4',
    services: ['New books', 'Second hand', 'Events', 'Special orders'],
    seoDescription: 'An independent bookshop with a hand-picked front table, second-hand room and a weekly events programme.',
    sections: [
      {
        kind: 'hero',
        heading: 'No algorithm chose this table',
        subheading: 'Four booksellers did, and they argue',
        body: 'New books at the front, second-hand up the stairs, and a chair you are welcome to sit in for an hour.',
        images: [heroImage('The front table')],
        callToAction: { label: 'This month', href: '#events' },
      },
      { kind: 'gallery', heading: 'The shop', images: galleryImages(5, 'Quire Books') },
      {
        kind: 'services',
        heading: 'What is here',
        bullets: [
          'New fiction and non-fiction',
          'Second-hand and antiquarian, first floor',
          'Children and young adult',
          'Special orders, usually next day',
        ],
      },
      { kind: 'about', heading: 'The shop', body: 'Open since 1974 and independent the whole time. The stairs are original, which is a polite way of saying steep.' },
      { kind: 'hours', heading: 'Open', bullets: ['Monday to Saturday, 09:30–18:00', 'Sunday, 11:00–16:00'] },
      { kind: 'contact', heading: 'Contact', bullets: ['books@example.test', '01865 000 000'] },
    ],
  },
  {
    slug: 'garden-centre',
    label: 'Garden centre',
    name: 'Wharram Nurseries',
    listingCategory: 'Garden center',
    strategyPrimary: 'Garden centre',
    strategySecondary: ['Retail', 'Horticulture'],
    tagline: 'Grown here, not shipped here',
    tone: 'friendly and knowledgeable',
    headingFont: 'Nunito Sans',
    bodyFont: 'Nunito Sans',
    services: ['Plants', 'Trees and hedging', 'Tools', 'Advice'],
    seoDescription: 'A working nursery growing most of what it sells: perennials, trees, hedging and bare-root in season.',
    sections: [
      {
        kind: 'hero',
        heading: 'Most of this was grown in that field',
        subheading: 'The one you drove past',
        body: 'Twelve acres under production. If it is not ours we will tell you whose it is.',
        images: [heroImage('The glasshouse')],
        callToAction: { label: 'What is ready', href: '#stock' },
      },
      { kind: 'gallery', heading: 'The nursery', images: galleryImages(6, 'Wharram Nurseries') },
      {
        kind: 'services',
        heading: 'In stock',
        bullets: [
          'Herbaceous perennials, grown on site',
          'Trees and hedging, bare-root November to March',
          'Roses, own-root',
          'Seed potatoes and onion sets, January',
          'Compost, peat free only',
        ],
      },
      { kind: 'hours', heading: 'Open', bullets: ['Every day, 09:00–17:00', 'Closed 24 December to 2 January'] },
      { kind: 'location', heading: 'Where', body: 'Wharram Lane, two miles off the A64' },
      { kind: 'contact', heading: 'Contact', bullets: ['plants@example.test', '01944 000 000'] },
    ],
  },
  {
    slug: 'bike-shop',
    label: 'Bike shop',
    name: 'Cadence Cycles',
    listingCategory: 'Bicycle shop',
    strategyPrimary: 'Bicycle retail and repair',
    strategySecondary: ['Retail', 'Workshop'],
    tagline: 'A workshop that happens to sell bikes',
    tone: 'practical and enthusiastic',
    headingFont: 'Manrope',
    bodyFont: 'Manrope',
    services: ['Servicing', 'Wheel building', 'New bikes', 'Bike fitting'],
    seoDescription: 'A bike shop built around its workshop: servicing, hand-built wheels, fitting and a small, chosen range.',
    sections: [
      {
        kind: 'hero',
        heading: 'The workshop came first',
        subheading: 'The shop floor is what fitted in around it',
        body: 'Two mechanics, four stands, and wheels built by hand on the bench you can see from the counter.',
        images: [heroImage('The workshop')],
        callToAction: { label: 'Book a service', href: '#contact' },
      },
      {
        kind: 'menu',
        heading: 'Workshop',
        bullets: ['Safety check — free', 'Standard service — 65.00', 'Full strip and rebuild — 190.00', 'Wheel build, per wheel — 70.00', 'Bike fit, two hours — 130.00'],
      },
      { kind: 'gallery', heading: 'On the bench', images: galleryImages(5, 'Cadence Cycles workshop') },
      { kind: 'hours', heading: 'Open', bullets: ['Tuesday to Saturday, 09:00–18:00', 'Closed Sunday and Monday'] },
      { kind: 'contact', heading: 'Contact', bullets: ['workshop@example.test', '0131 000 0000'] },
    ],
  },
  {
    slug: 'pet-grooming',
    label: 'Pet grooming',
    name: 'Scruffs & Co',
    listingCategory: 'Pet groomer',
    strategyPrimary: 'Pet grooming',
    strategySecondary: ['Pet services'],
    tagline: 'One dog at a time, no cages',
    tone: 'playful and caring',
    headingFont: 'Fredoka',
    bodyFont: 'Nunito',
    services: ['Full groom', 'Bath and brush', 'Puppy introduction', 'Hand stripping'],
    seoDescription: 'A one-dog-at-a-time grooming salon with no cages, offering full grooms, hand stripping and puppy visits.',
    sections: [
      {
        kind: 'hero',
        heading: 'Your dog is the only dog here',
        subheading: 'No cages, no waiting around',
        body: 'One appointment at a time. They arrive, they are groomed, they go home — usually inside two hours.',
        images: [heroImage('The grooming room')],
        callToAction: { label: 'Book a groom', href: '#contact' },
      },
      {
        kind: 'menu',
        heading: 'Prices',
        bullets: ['Bath and brush, small — 30.00', 'Full groom, small — 45.00', 'Full groom, large — 70.00', 'Hand stripping — from 65.00', 'Puppy introduction — free'],
      },
      { kind: 'gallery', heading: 'Before and after', images: galleryImages(6, 'Groomed at Scruffs') },
      { kind: 'contact', heading: 'Contact', bullets: ['woof@example.test', '07700 000000'] },
    ],
  },
  {
    slug: 'funeral-director',
    label: 'Funeral director',
    name: 'Ellwood & Daughters',
    listingCategory: 'Funeral home',
    strategyPrimary: 'Funeral directors',
    strategySecondary: ['Professional services'],
    tagline: 'Family run, four generations',
    tone: 'formal and compassionate',
    headingFont: 'Lora',
    bodyFont: 'Source Sans 3',
    services: ['Funerals', 'Pre-paid plans', 'Repatriation', 'Memorials'],
    seoDescription: 'A family-run firm of funeral directors, established 1911, with a traditional chapel of rest and pre-paid plans.',
    sections: [
      {
        kind: 'hero',
        heading: 'There is no wrong question',
        subheading: 'Someone will answer, at any hour',
        body: 'A traditional, established family firm. We will explain what has to happen next, and then only what you ask for.',
        images: [heroImage('The chapel of rest')],
        callToAction: { label: 'Speak to us', href: '#contact' },
      },
      {
        kind: 'services',
        heading: 'How we help',
        bullets: [
          'Funerals, burial and cremation',
          'Direct cremation, without a service',
          'Pre-paid funeral plans',
          'Repatriation, to and from abroad',
          'Memorials and headstones',
        ],
      },
      { kind: 'about', heading: 'The firm', body: 'Established in 1911 and run by the same family since. The name changed in 1994, when the daughters took over.' },
      { kind: 'contact', heading: 'Contact', bullets: ['Any hour — 0114 000 0000', 'office@example.test'] },
    ],
  },
  {
    slug: 'art-gallery',
    label: 'Art gallery',
    name: 'Pale Green Gallery',
    listingCategory: 'Art gallery',
    strategyPrimary: 'Art gallery',
    strategySecondary: ['Arts', 'Culture'],
    tagline: 'Six shows a year, no permanent collection',
    tone: 'editorial and considered',
    headingFont: 'Playfair Display',
    bodyFont: 'Source Serif 4',
    services: ['Exhibitions', 'Artist representation', 'Editions', 'Talks'],
    seoDescription: 'A contemporary gallery running six exhibitions a year, representing eleven artists, with a print editions programme.',
    sections: [
      {
        kind: 'hero',
        heading: 'Nothing here is permanent',
        subheading: 'Six shows a year and then the walls are white again',
        body: 'We represent eleven artists and show all of them. Everything on the wall is for sale and the price is on the list by the door.',
        images: [heroImage('The main room')],
        callToAction: { label: 'Current show', href: '#exhibitions' },
      },
      { kind: 'gallery', heading: 'Installation views', images: galleryImages(9, 'Pale Green Gallery') },
      { kind: 'about', heading: 'The gallery', body: 'Opened in 2016 in a former print works. Two rooms, nine hundred square feet, and a north light we did not have to install.' },
      { kind: 'hours', heading: 'Open', bullets: ['Thursday to Saturday, 11:00–18:00', 'Sunday, 12:00–16:00', 'And by appointment'] },
      { kind: 'contact', heading: 'Contact', bullets: ['gallery@example.test'] },
    ],
  },
  {
    slug: 'wedding-venue',
    label: 'Wedding venue',
    name: 'Thornbury Barn',
    listingCategory: 'Wedding venue',
    strategyPrimary: 'Wedding venue',
    strategySecondary: ['Events', 'Hospitality'],
    tagline: 'One wedding a weekend, exclusively yours',
    tone: 'romantic and exclusive',
    headingFont: 'Cormorant Garamond',
    bodyFont: 'Jost',
    services: ['Ceremony', 'Reception', 'Accommodation', 'Exclusive hire'],
    seoDescription: 'An exclusive-use wedding venue in a restored threshing barn, licensed for ceremonies, sleeping twenty-four.',
    sections: [
      {
        kind: 'hero',
        heading: 'You will not see another party',
        subheading: 'One wedding a weekend, the whole estate',
        body: 'A bespoke, exclusive hire: the barn, the walled garden and the cottages, from Friday noon to Sunday noon.',
        images: [heroImage('The barn at dusk')],
        callToAction: { label: 'Check dates', href: '#contact' },
      },
      { kind: 'gallery', heading: 'The estate', images: galleryImages(8, 'Thornbury Barn') },
      {
        kind: 'services',
        heading: 'Included',
        bullets: [
          'Exclusive use, Friday to Sunday',
          'Licensed ceremony, indoors or in the garden',
          'Reception for one hundred and forty',
          'Accommodation for twenty-four',
          'Your own caterer, or one of ours',
        ],
      },
      { kind: 'testimonials', heading: 'Couples', bullets: ['"We arrived on the Friday and it genuinely felt like ours." — A. and R. Sowerby'] },
      { kind: 'contact', heading: 'Enquiries', bullets: ['weddings@example.test', '01454 000 000'] },
    ],
  },
  {
    slug: 'accountant-boutique',
    label: 'Tax advisory',
    name: 'Kestrel Tax',
    listingCategory: 'Tax consultant',
    strategyPrimary: 'Tax advisory',
    strategySecondary: ['Professional services', 'Finance'],
    tagline: 'Complex affairs, plain answers',
    tone: 'formal and precise',
    headingFont: 'IBM Plex Sans',
    bodyFont: 'IBM Plex Sans',
    services: ['Personal tax', 'Trusts and estates', 'Non-domicile', 'HMRC enquiries'],
    seoDescription: 'A specialist tax advisory practice covering personal tax, trusts and estates, non-domicile matters and HMRC enquiries.',
    sections: [
      {
        kind: 'hero',
        heading: 'An established practice for complicated returns',
        subheading: 'Personal tax, trusts, and the awkward ones',
        body: 'Most of our work arrives because something has already gone wrong. That is a normal way to meet us.',
        images: [heroImage('The office')],
        callToAction: { label: 'Arrange a call', href: '#contact' },
      },
      {
        kind: 'services',
        heading: 'What we advise on',
        bullets: [
          'Personal tax and self assessment',
          'Trusts, estates and inheritance tax',
          'Residence and non-domicile',
          'Capital gains on property and shares',
          'HMRC enquiries and disclosures',
        ],
      },
      { kind: 'faq', heading: 'Common questions', bullets: ['Do you take one-off work? Yes.', 'Can you deal with HMRC directly? With authority, yes.', 'How are fees set? Fixed, agreed before we start.'] },
      { kind: 'contact', heading: 'Contact', bullets: ['advice@example.test', '020 0000 0000'] },
    ],
  },
];
