/**
 * Vendors the theme library's typefaces into the repository, once.
 *
 *   npx tsx scripts/vendor-fonts.ts
 *
 * Writes `assets/fonts/<family>-<weight>.woff2` plus a `manifest.json`. The
 * renderer reads those files and base64-inlines only the faces the design
 * actually uses, so a rendered site still opens from disk and still makes no
 * external request — the fetch happens here, at author time, not there.
 *
 * Latin subset only. The unicode-range Google serves for `latin` is the one
 * every generated site's copy falls inside, and pulling cyrillic and greek for
 * eighteen families would triple the bytes to serve characters no page uses.
 *
 * Re-running is idempotent: a face already on disk is left alone, so the
 * manifest's hashes stay stable and the rendered CSS stays byte-comparable.
 */

import path from 'node:path';
import { fileURLToPath } from 'node:url';
import fs from 'node:fs/promises';

import { THEMES } from '../lib/design/themes.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const FONT_DIR = path.join(ROOT, 'assets', 'fonts');

/** A browser UA, because the css2 endpoint serves TTF to anything it doesn't know. */
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
  + '(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

/** Every family the theme library names, with the union of weights it asks for. */
function required(): Map<string, Set<number>> {
  const out = new Map<string, Set<number>>();
  const add = (family: string, weights: readonly number[]): void => {
    const set = out.get(family) ?? new Set<number>();
    for (const weight of weights) set.add(weight);
    out.set(family, set);
  };

  for (const theme of Object.values(THEMES)) {
    add(theme.headingFont.family, theme.headingFont.weights);
    add(theme.bodyFont.family, theme.bodyFont.weights);
    if (theme.monoFont !== null) add(theme.monoFont.family, theme.monoFont.weights);
  }
  return out;
}

export function slugify(family: string): string {
  return family.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

/**
 * The `latin` block of a css2 response, as weight → URL.
 *
 * Google emits one `@font-face` per (weight, subset) with a comment naming the
 * subset above it. The comment is the only thing distinguishing the blocks, so
 * it is what the split keys on.
 */
function parseLatin(css: string): Map<number, string> {
  const out = new Map<number, string>();

  for (const block of css.split('/*').slice(1)) {
    const subset = block.slice(0, block.indexOf('*/')).trim();
    if (subset !== 'latin') continue;

    const weight = /font-weight:\s*(\d+)/.exec(block)?.[1];
    const url = /src:\s*url\((https:[^)]+\.woff2)\)/.exec(block)?.[1];
    if (weight === undefined || url === undefined) continue;
    out.set(Number(weight), url);
  }
  return out;
}

async function fetchText(url: string): Promise<string> {
  const response = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!response.ok) throw new Error(`${response.status} ${response.statusText} for ${url}`);
  return response.text();
}

async function fetchBinary(url: string): Promise<Buffer> {
  const response = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!response.ok) throw new Error(`${response.status} ${response.statusText} for ${url}`);
  return Buffer.from(await response.arrayBuffer());
}

interface ManifestEntry {
  readonly family: string;
  readonly weight: number;
  readonly file: string;
  readonly bytes: number;
}

/**
 * The manifest as a TypeScript module.
 *
 * The renderer is a pure function and may not read a file, so what it needs to
 * know about the vendored faces has to reach it as source. Generated rather
 * than hand-kept: a face on disk that the module does not list would silently
 * fall back to Georgia, and one the module lists that is not on disk would 404.
 */
async function writeManifestModule(entries: readonly ManifestEntry[]): Promise<void> {
  const rows = entries
    .map((entry) => `  { family: '${entry.family.replace(/'/g, "\\'")}', weight: ${entry.weight}, file: '${entry.file}' },`)
    .join('\n');

  const source = `/**
 * The vendored typefaces — GENERATED by \`scripts/vendor-fonts.ts\`. Do not edit.
 *
 * One entry per (family, weight) woff2 in \`assets/fonts/\`, latin subset. The
 * renderer emits an \`@font-face\` for the handful a design actually uses and
 * declares the files as assets; nothing here is fetched at render time.
 */

export interface VendoredFace {
  readonly family: string;
  readonly weight: number;
  /** File name inside the font directory. */
  readonly file: string;
}

export const VENDORED_FACES: readonly VendoredFace[] = [
${rows}
];
`;

  await fs.writeFile(path.join(ROOT, 'lib', 'render', 'fontManifest.ts'), source, 'utf8');
}

async function main(): Promise<void> {
  await fs.mkdir(FONT_DIR, { recursive: true });

  const wanted = required();
  const manifest: ManifestEntry[] = [];
  let fetched = 0;
  let reused = 0;

  // Sorted so the manifest is stable whatever order the themes declare in.
  for (const family of [...wanted.keys()].sort()) {
    const weights = [...(wanted.get(family) ?? new Set<number>())].sort((a, b) => a - b);
    const query = `family=${encodeURIComponent(family)}:wght@${weights.join(';')}&display=swap`;

    let latin: Map<number, string>;
    try {
      latin = parseLatin(await fetchText(`https://fonts.googleapis.com/css2?${query}`));
    } catch (error) {
      console.error(`  ! ${family}: ${(error as Error).message}`);
      continue;
    }

    for (const weight of weights) {
      const file = `${slugify(family)}-${weight}.woff2`;
      const target = path.join(FONT_DIR, file);

      const existing = await fs.stat(target).catch(() => null);
      if (existing !== null && existing.size > 0) {
        manifest.push({ family, weight, file, bytes: existing.size });
        reused += 1;
        continue;
      }

      // Google collapses a variable family to the nearest served weight; taking
      // the closest available is better than dropping the face and falling back
      // to Georgia for a heading the theme specified at 800.
      const url = latin.get(weight)
        ?? [...latin.entries()].sort((a, b) => Math.abs(a[0] - weight) - Math.abs(b[0] - weight))[0]?.[1];

      if (url === undefined) {
        console.error(`  ! ${family} ${weight}: no latin face served`);
        continue;
      }

      const bytes = await fetchBinary(url);
      await fs.writeFile(target, bytes);
      manifest.push({ family, weight, file, bytes: bytes.length });
      fetched += 1;
    }
    console.log(`  ${family} — ${weights.join(', ')}`);
  }

  manifest.sort((a, b) => a.family.localeCompare(b.family) || a.weight - b.weight);
  await fs.writeFile(
    path.join(FONT_DIR, 'manifest.json'),
    `${JSON.stringify({ subset: 'latin', faces: manifest }, null, 2)}\n`,
    'utf8',
  );
  await writeManifestModule(manifest);

  const total = manifest.reduce((sum, entry) => sum + entry.bytes, 0);
  console.log(`\n${manifest.length} faces (${fetched} fetched, ${reused} reused), ${Math.round(total / 1024)} KB total.`);
}

await main();
